---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  #namespace: sprint
  labels:
   app: mongodb
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: mongodb
...
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
     # terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: rajmandale/capstone:mongo
        
        ports:
        - containerPort: 27017
        
...
